package de.psekochbuch.exzellenzkoch.datalayer.repositoryimplementations
import de.psekochbuch.exzellenzkoch.datalayer.repository.IngredientChapterRepository

class IngredientChapterRepositoryImplementation :IngredientChapterRepository{
}