package com.example.kochbuchappmagnus.datalayer.repositoryimpl.repository

import de.psekochbuch.exzellenzkoch.datalayer.repository.PublicRecipeRepository

class PublicRecipeRepositoryImplementation :PublicRecipeRepository{
}