package de.psekochbuch.exzellenzkoch.datalayer.repositoryimplementations
import de.psekochbuch.exzellenzkoch.datalayer.repository.PublicRecipeRepository

class PublicRecipeRepositoryImplementation :PublicRecipeRepository{
}