package de.psekochbuch.exzellenzkoch.userinterfacelayer.viewmodel.factories

import de.psekochbuch.exzellenzkoch.domainlayer.interfaces.repository.UserRepository

class ProfileEditViewModelFactory(repo:UserRepository)